allowBuilds:
  better-sqlite3: true
  esbuild: true
  rolldown: true
  sharp: true
  '@parcel/watcher': false
  puppeteer: false
  vue-demi: false
minimumReleaseAgeExclude:
  - '@j178/prek-android-arm64@0.4.3'
  - '@j178/prek-darwin-arm64@0.4.3'
  - '@j178/prek-darwin-x64@0.4.3'
  - '@j178/prek-linux-arm-gnueabihf@0.4.3'
  - '@j178/prek-linux-arm-musleabihf@0.4.3'
  - '@j178/prek-linux-arm64-gnu@0.4.3'
  - '@j178/prek-linux-arm64-musl@0.4.3'
  - '@j178/prek-linux-armv7-musleabihf@0.4.3'
  - '@j178/prek-linux-ia32-gnu@0.4.3'
  - '@j178/prek-linux-ia32-musl@0.4.3'
  - '@j178/prek-linux-riscv64-gnu@0.4.3'
  - '@j178/prek-linux-s390x-gnu@0.4.3'
  - '@j178/prek-linux-x64-gnu@0.4.3'
  - '@j178/prek-linux-x64-musl@0.4.3'
  - '@j178/prek-win32-arm64-msvc@0.4.3'
  - '@j178/prek-win32-ia32-msvc@0.4.3'
  - '@j178/prek-win32-x64-msvc@0.4.3'
  - '@j178/prek@0.4.3'
