import { defineConfig } from 'vitest/config'
import { defineVitestProject } from '@nuxt/test-utils/config'

export default defineConfig({
  test: {
    projects: [
      {
        test: {
          name: 'unit',
          include: ['test/{e2e,unit}/*.{test,spec}.ts'],
          environment: 'node',
        },
      },
      await defineVitestProject({
        test: {
          name: 'nuxt',
          include: ['test/nuxt/*.{test,spec}.ts'],
          environment: 'nuxt',
        },
      }),
      {
        // Static-artifact scan: reads dist/ (generated by `pnpm generate`).
        // Excluded from `test-all` because it requires a fresh build —
        // invoke via `pnpm test-build` after `pnpm run generate` /
        // `pnpm run generate-github`.
        test: {
          name: 'build',
          include: ['test/build/*.{test,spec}.ts'],
          environment: 'node',
        },
      },
    ],
  },
})
