<script setup lang="ts">
import type { Plugin } from '~/types'
import { PluginProseA, PluginProseKbd, PluginProseImg } from '#components'
import { parseMarkdown } from '@nuxtjs/mdc/runtime'
import { useAsyncData } from '#imports'

definePageMeta({
  heroBackground: 'opacity-30 -z-10'
})
const route = useRoute()

const { default: pluginsData } = await import('~/data/plugins.json')
const plugin = ref<Plugin | null>(pluginsData.find((p: Plugin) => p.key === route.params.slug) || null)

// Fetch README from GitHub
const readme = ref<any>(null)

readme.value = atob("PCEtLSBtYXJrZG93bmxpbnQtZGlzYWJsZSAtLT4KPHAgYWxpZ249ImNlbnRl\nciI+CiAgPCEtLSBnaXRodWItYmFubmVyLXN0YXJ0IC0tPgogIDxpbWcgc3Jj\nPSJodHRwczovL3Jhdy5naXRodWJ1c2VyY29udGVudC5jb20vbGl0ZXN0YXIt\nb3JnL2JyYW5kaW5nL21haW4vYXNzZXRzL0JyYW5kaW5nJTIwLSUyMFNWRyUy\nMC0lMjBUcmFuc3BhcmVudC9BQSUyMC0lMjBCYW5uZXIlMjAtJTIwSW5saW5l\nJTIwLSUyMExpZ2h0LnN2ZyNnaC1saWdodC1tb2RlLW9ubHkiIGFsdD0iTGl0\nZXN0YXIgTG9nbyAtIExpZ2h0IiB3aWR0aD0iMTAwJSIgaGVpZ2h0PSJhdXRv\nIiAvPgogIDxpbWcgc3JjPSJodHRwczovL3Jhdy5naXRodWJ1c2VyY29udGVu\ndC5jb20vbGl0ZXN0YXItb3JnL2JyYW5kaW5nL21haW4vYXNzZXRzL0JyYW5k\naW5nJTIwLSUyMFNWRyUyMC0lMjBUcmFuc3BhcmVudC9BQSUyMC0lMjBCYW5u\nZXIlMjAtJTIwSW5saW5lJTIwLSUyMERhcmsuc3ZnI2doLWRhcmstbW9kZS1v\nbmx5IiBhbHQ9IkxpdGVzdGFyIExvZ28gLSBEYXJrIiB3aWR0aD0iMTAwJSIg\naGVpZ2h0PSJhdXRvIiAvPgogIDwhLS0gZ2l0aHViLWJhbm5lci1lbmQgLS0+\nCjwvcD4KPGRpdiBhbGlnbj0iY2VudGVyIj4KPCEtLSBtYXJrZG93bmxpbnQt\ncmVzdG9yZSAtLT4KCjwhLS0gcHJldHRpZXItaWdub3JlLXN0YXJ0IC0tPgoK\nfCBQcm9qZWN0ICAgfCAgICAgfCBTdGF0dXMgICAgICAgICAgICAgICAgICAg\nICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAg\nICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAg\nICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAg\nICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAg\nICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAg\nICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAg\nICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAg\nICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAg\nICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAg\nICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAg\nICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAg\nICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAg\nICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAg\nICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAg\nICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAg\nICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAg\nICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAg\nICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAg\nICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAg\nICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAg\nICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAg\nICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAg\nICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAg\nICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIHwKfC0tLS0tLS0tLS0t\nfDotLS0tfC0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0t\nLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0t\nLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0t\nLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0t\nLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0t\nLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0t\nLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0t\nLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0t\nLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0t\nLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0t\nLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0t\nLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0t\nLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0t\nLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0t\nLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0t\nLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0t\nLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0t\nLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0t\nLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0t\nLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0t\nLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0t\nLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0t\nLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0t\nLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0t\nLS0tLS0tLS0tLS0tLS0tLS0tLXwKfCBDSS9DRCAgICAgfCAgICAgfCBbIVtM\nYXRlc3QgUmVsZWFzZV0oaHR0cHM6Ly9naXRodWIuY29tL2xpdGVzdGFyLW9y\nZy9hZHZhbmNlZC1hbGNoZW15L2FjdGlvbnMvd29ya2Zsb3dzL3B1Ymxpc2gu\neW1sL2JhZGdlLnN2ZyldKGh0dHBzOi8vZ2l0aHViLmNvbS9saXRlc3Rhci1v\ncmcvYWR2YW5jZWQtYWxjaGVteS9hY3Rpb25zL3dvcmtmbG93cy9wdWJsaXNo\nLnltbCkgWyFbY2ldKGh0dHBzOi8vZ2l0aHViLmNvbS9saXRlc3Rhci1vcmcv\nYWR2YW5jZWQtYWxjaGVteS9hY3Rpb25zL3dvcmtmbG93cy9jaS55bWwvYmFk\nZ2Uuc3ZnKV0oaHR0cHM6Ly9naXRodWIuY29tL2xpdGVzdGFyLW9yZy9hZHZh\nbmNlZC1hbGNoZW15L2FjdGlvbnMvd29ya2Zsb3dzL2NpLnltbCkgWyFbRG9j\ndW1lbnRhdGlvbiBCdWlsZGluZ10oaHR0cHM6Ly9naXRodWIuY29tL2xpdGVz\ndGFyLW9yZy9hZHZhbmNlZC1hbGNoZW15L2FjdGlvbnMvd29ya2Zsb3dzL2Rv\nY3MueW1sL2JhZGdlLnN2Zz9icmFuY2g9bWFpbildKGh0dHBzOi8vZ2l0aHVi\nLmNvbS9saXRlc3Rhci1vcmcvYWR2YW5jZWQtYWxjaGVteS9hY3Rpb25zL3dv\ncmtmbG93cy9kb2NzLnltbCkgICAgICAgICAgICAgICAgICAgICAgICAgICAg\nICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAg\nICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAg\nICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAg\nICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAg\nICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAg\nICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAg\nICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAg\nICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAg\nICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAg\nICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAg\nICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAg\nICAgICAgIHwKfCBRdWFsaXR5ICAgfCAgICAgfCBbIVtDb3ZlcmFnZV0oaHR0\ncHM6Ly9jb2RlY292LmlvL2dpdGh1Yi9saXRlc3Rhci1vcmcvYWR2YW5jZWQt\nYWxjaGVteS9ncmFwaC9iYWRnZS5zdmc/dG9rZW49dktlejRQeWNyYyldKGh0\ndHBzOi8vY29kZWNvdi5pby9naXRodWIvbGl0ZXN0YXItb3JnL2FkdmFuY2Vk\nLWFsY2hlbXkpIFshW1F1YWxpdHkgR2F0ZSBTdGF0dXNdKGh0dHBzOi8vc29u\nYXJjbG91ZC5pby9hcGkvcHJvamVjdF9iYWRnZXMvbWVhc3VyZT9wcm9qZWN0\nPWxpdGVzdGFyLW9yZ19hZHZhbmNlZC1hbGNoZW15Jm1ldHJpYz1hbGVydF9z\ndGF0dXMpXShodHRwczovL3NvbmFyY2xvdWQuaW8vc3VtbWFyeS9uZXdfY29k\nZT9pZD1saXRlc3Rhci1vcmdfYWR2YW5jZWQtYWxjaGVteSkgWyFbTWFpbnRh\naW5hYmlsaXR5IFJhdGluZ10oaHR0cHM6Ly9zb25hcmNsb3VkLmlvL2FwaS9w\ncm9qZWN0X2JhZGdlcy9tZWFzdXJlP3Byb2plY3Q9bGl0ZXN0YXItb3JnX2Fk\ndmFuY2VkLWFsY2hlbXkmbWV0cmljPXNxYWxlX3JhdGluZyldKGh0dHBzOi8v\nc29uYXJjbG91ZC5pby9zdW1tYXJ5L25ld19jb2RlP2lkPWxpdGVzdGFyLW9y\nZ19hZHZhbmNlZC1hbGNoZW15KSBbIVtSZWxpYWJpbGl0eSBSYXRpbmddKGh0\ndHBzOi8vc29uYXJjbG91ZC5pby9hcGkvcHJvamVjdF9iYWRnZXMvbWVhc3Vy\nZT9wcm9qZWN0PWxpdGVzdGFyLW9yZ19hZHZhbmNlZC1hbGNoZW15Jm1ldHJp\nYz1yZWxpYWJpbGl0eV9yYXRpbmcpXShodHRwczovL3NvbmFyY2xvdWQuaW8v\nc3VtbWFyeS9uZXdfY29kZT9pZD1saXRlc3Rhci1vcmdfYWR2YW5jZWQtYWxj\naGVteSkgWyFbU2VjdXJpdHkgUmF0aW5nXShodHRwczovL3NvbmFyY2xvdWQu\naW8vYXBpL3Byb2plY3RfYmFkZ2VzL21lYXN1cmU/cHJvamVjdD1saXRlc3Rh\nci1vcmdfYWR2YW5jZWQtYWxjaGVteSZtZXRyaWM9c2VjdXJpdHlfcmF0aW5n\nKV0oaHR0cHM6Ly9zb25hcmNsb3VkLmlvL3N1bW1hcnkvbmV3X2NvZGU/aWQ9\nbGl0ZXN0YXItb3JnX2FkdmFuY2VkLWFsY2hlbXkpICAgICAgICAgICAgICAg\nICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAg\nICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIHwKfCBQ\nYWNrYWdlICAgfCAgICAgfCBbIVtQeVBJIC0gVmVyc2lvbl0oaHR0cHM6Ly9p\nbWcuc2hpZWxkcy5pby9weXBpL3YvYWR2YW5jZWQtYWxjaGVteT9sYWJlbENv\nbG9yPTIwMjIzNSZjb2xvcj1lZGI2NDEmbG9nbz1weXRob24mbG9nb0NvbG9y\nPWVkYjY0MSldKGh0dHBzOi8vYmFkZ2UuZnVyeS5pby9weS9hZHZhbmNlZC1h\nbGNoZW15KSAhW1B5UEkgLSBTdXBwb3J0IFB5dGhvbiBWZXJzaW9uc10oaHR0\ncHM6Ly9pbWcuc2hpZWxkcy5pby9weXBpL3B5dmVyc2lvbnMvYWR2YW5jZWQt\nYWxjaGVteT9sYWJlbENvbG9yPTIwMjIzNSZjb2xvcj1lZGI2NDEmbG9nbz1w\neXRob24mbG9nb0NvbG9yPWVkYjY0MSkgIVtBZHZhbmNlZCBBbGNoZW15IFB5\nUEkgLSBEb3dubG9hZHNdKGh0dHBzOi8vaW1nLnNoaWVsZHMuaW8vcHlwaS9k\nbS9hZHZhbmNlZC1hbGNoZW15P2xvZ289cHl0aG9uJmxhYmVsPXBhY2thZ2Ul\nMjBkb3dubG9hZHMmbGFiZWxDb2xvcj0yMDIyMzUmY29sb3I9ZWRiNjQxJmxv\nZ29Db2xvcj1lZGI2NDEpICAgICAgICAgICAgICAgICAgICAgICAgICAgICAg\nICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAg\nICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAg\nICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAg\nICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAg\nICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAg\nICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAg\nICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAg\nICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAg\nICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAg\nICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAg\nICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAg\nICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAg\nICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICB8\nCnwgQ29tbXVuaXR5IHwgICAgIHwgWyFbRGlzY29yZF0oaHR0cHM6Ly9pbWcu\nc2hpZWxkcy5pby9kaXNjb3JkLzkxOTE5MzQ5NTExNjMzNzE1ND9sYWJlbENv\nbG9yPTIwMjIzNSZjb2xvcj1lZGI2NDEmbGFiZWw9Y2hhdCUyMG9uJTIwZGlz\nY29yZCZsb2dvPWRpc2NvcmQmbG9nb0NvbG9yPWVkYjY0MSldKGh0dHBzOi8v\nZGlzY29yZC5nZy9saXRlc3RhcikgWyFbTWF0cml4XShodHRwczovL2ltZy5z\naGllbGRzLmlvL2JhZGdlL2NoYXQlMjBvbiUyME1hdHJpeC1icmlkZ2VkLTIw\nMjIzNT9sYWJlbENvbG9yPTIwMjIzNSZjb2xvcj1lZGI2NDEmbG9nbz1tYXRy\naXgmbG9nb0NvbG9yPWVkYjY0MSldKGh0dHBzOi8vbWF0cml4LnRvLyMvI2xp\ndGVzdGFyOm1hdHJpeC5vcmcpIHwKfCBNZXRhICAgICAgfCAgICAgfCBbIVtM\naXRlc3RhciBQcm9qZWN0XShodHRwczovL2ltZy5zaGllbGRzLmlvL2JhZGdl\nL0xpdGVzdGFyJTIwT3JnLSVFMiVBRCU5MCUyMEFkdmFuY2VkJTIwQWxjaGVt\neS0yMDIyMzUuc3ZnP2xvZ289cHl0aG9uJmxhYmVsQ29sb3I9MjAyMjM1JmNv\nbG9yPWVkYjY0MSZsb2dvQ29sb3I9ZWRiNjQxKV0oaHR0cHM6Ly9naXRodWIu\nY29tL2xpdGVzdGFyLW9yZy9hZHZhbmNlZC1hbGNoZW15KSBbIVt0eXBlcyAt\nIE15cHldKGh0dHBzOi8vaW1nLnNoaWVsZHMuaW8vYmFkZ2UvdHlwZXMtTXlw\neS0yMDIyMzUuc3ZnP2xvZ289cHl0aG9uJmxhYmVsQ29sb3I9MjAyMjM1JmNv\nbG9yPWVkYjY0MSZsb2dvQ29sb3I9ZWRiNjQxKV0oaHR0cHM6Ly9naXRodWIu\nY29tL3B5dGhvbi9teXB5KSBbIVtMaWNlbnNlIC0gTUlUXShodHRwczovL2lt\nZy5zaGllbGRzLmlvL2JhZGdlL2xpY2Vuc2UtTUlULTIwMjIzNS5zdmc/bG9n\nbz1weXRob24mbGFiZWxDb2xvcj0yMDIyMzUmY29sb3I9ZWRiNjQxJmxvZ29D\nb2xvcj1lZGI2NDEpXShodHRwczovL3NwZHgub3JnL2xpY2Vuc2VzLykgWyFb\nbGludGluZyAtIFJ1ZmZdKGh0dHBzOi8vaW1nLnNoaWVsZHMuaW8vZW5kcG9p\nbnQ/dXJsPWh0dHBzOi8vcmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbS9jaGFy\nbGllcm1hcnNoL3J1ZmYvbWFpbi9hc3NldHMvYmFkZ2UvdjIuanNvbiZsYWJl\nbENvbG9yPTIwMjIzNSldKGh0dHBzOi8vZ2l0aHViLmNvbS9hc3RyYWwtc2gv\ncnVmZikgfAoKPC9kaXY+CgojIEFkdmFuY2VkIEFsY2hlbXkKCkNoZWNrIG91\ndCB0aGUgW3Byb2plY3QgZG9jdW1lbnRhdGlvbl1bcHJvamVjdC1kb2NzXSDw\nn5OaIGZvciBtb3JlIGluZm9ybWF0aW9uLgoKIyMgQWJvdXQKCkEgY2FyZWZ1\nbGx5IGNyYWZ0ZWQsIHRob3JvdWdobHkgdGVzdGVkLCBvcHRpbWl6ZWQgY29t\ncGFuaW9uIGxpYnJhcnkgZm9yIFNRTEFsY2hlbXksCm9mZmVyaW5nOgoKLSBT\neW5jIGFuZCBhc3luYyByZXBvc2l0b3JpZXMsIGZlYXR1cmluZyBjb21tb24g\nQ1JVRCBhbmQgaGlnaGx5IG9wdGltaXplZCBidWxrIG9wZXJhdGlvbnMKLSBJ\nbnRlZ3JhdGlvbiB3aXRoIG1ham9yIHdlYiBmcmFtZXdvcmtzIGluY2x1ZGlu\nZyBMaXRlc3RhciwgU3RhcmxldHRlLCBGYXN0QVBJLCBTYW5pYwotIEN1c3Rv\nbS1idWlsdCBhbGVtYmljIGNvbmZpZ3VyYXRpb24gYW5kIENMSSB3aXRoIG9w\ndGlvbmFsIGZyYW1ld29yayBpbnRlZ3JhdGlvbgotIFV0aWxpdHkgYmFzZSBj\nbGFzc2VzIHdpdGggYXVkaXQgY29sdW1ucywgcHJpbWFyeSBrZXlzIGFuZCB1\ndGlsaXR5IGZ1bmN0aW9ucwotIEJ1aWx0IGluIGBGaWxlIE9iamVjdGAgZGF0\nYSB0eXBlIGZvciBzdG9yaW5nIG9iamVjdHM6CiAgICAtIFVuaWZpZWQgaW50\nZXJmYWNlIGZvciB2YXJpb3VzIHN0b3JhZ2UgYmFja2VuZHMgKFtgZnNzcGVj\nYF0oaHR0cHM6Ly9maWxlc3lzdGVtLXNwZWMucmVhZHRoZWRvY3MuaW8vZW4v\nbGF0ZXN0LykgYW5kIFtgb2JzdG9yZWBdKGh0dHBzOi8vZGV2ZWxvcG1lbnRz\nZWVkLm9yZy9vYnN0b3JlL2xhdGVzdC8pKQogICAgLSBPcHRpb25hbCBsaWZl\nY3ljbGUgZXZlbnQgaG9va3MgaW50ZWdyYXRlZCB3aXRoIFNRTEFsY2hlbXkn\ncyBldmVudCBzeXN0ZW0gdG8gYXV0b21hdGljYWxseSBzYXZlIGFuZCBkZWxl\ndGUgZmlsZXMgYXMgcmVjb3JkcyBhcmUgaW5zZXJ0ZWQsIHVwZGF0ZWQsIG9y\nIGRlbGV0ZWQuCi0gT3B0aW1pemVkIEpTT04gdHlwZXMgaW5jbHVkaW5nIGEg\nY3VzdG9tIEpTT04gdHlwZSBmb3IgT3JhY2xlCi0gSW50ZWdyYXRlZCBzdXBw\nb3J0IGZvciBVVUlENiBhbmQgVVVJRDcgdXNpbmcgW2B1dWlkLXV0aWxzYF0o\naHR0cHM6Ly9naXRodWIuY29tL2FtaW5hbGFlZS91dWlkLXV0aWxzKSAoaW5z\ndGFsbCB3aXRoIHRoZSBgdXVpZGAgZXh0cmEpCi0gSW50ZWdyYXRlZCBzdXBw\nb3J0IGZvciBOYW5vIElEIHVzaW5nIFtgZmFzdG5hbm9pZGBdKGh0dHBzOi8v\nZ2l0aHViLmNvbS9vbGl2ZXJsYW1ic29uL2Zhc3RuYW5vaWQpIChpbnN0YWxs\nIHdpdGggdGhlIGBuYW5vaWRgIGV4dHJhKQotIEN1c3RvbSBlbmNyeXB0ZWQg\ndGV4dCB0eXBlIHdpdGggbXVsdGlwbGUgYmFja2VuZCBzdXBwb3J0IGluY2x1\nZGluZyBbYHBnY3J5cHRvYF0oaHR0cHM6Ly93d3cucG9zdGdyZXNxbC5vcmcv\nZG9jcy9jdXJyZW50L3BnY3J5cHRvLmh0bWwpIGZvciBQb3N0Z3JlU1FMIGFu\nZCB0aGUgRmVybmV0IGltcGxlbWVudGF0aW9uIGZyb20gW2BjcnlwdG9ncmFw\naHlgXShodHRwczovL2NyeXB0b2dyYXBoeS5pby9lbi9sYXRlc3QvKSBmb3Ig\nb3RoZXIgZGF0YWJhc2VzCi0gQ3VzdG9tIHBhc3N3b3JkIGhhc2hpbmcgdHlw\nZSB3aXRoIG11bHRpcGxlIGJhY2tlbmQgc3VwcG9ydCBpbmNsdWRpbmcgW2BB\ncmdvbjJgXShodHRwczovL2dpdGh1Yi5jb20vUC1ILUMvcGhjLXdpbm5lci1h\ncmdvbjIpLCBbYFBhc3NsaWJgXShodHRwczovL3Bhc3NsaWIucmVhZHRoZWRv\nY3MuaW8vZW4vc3RhYmxlLyksIGFuZCBbYFB3ZGxpYmBdKGh0dHBzOi8vcHdk\nbGliLnJlYWR0aGVkb2NzLmlvL2VuL3N0YWJsZS8pIHdpdGggYXV0b21hdGlj\nIHNhbHQgZ2VuZXJhdGlvbgotIFByZS1jb25maWd1cmVkIGJhc2UgY2xhc3Nl\ncyB3aXRoIGF1ZGl0IGNvbHVtbnMgVVVJRCBvciBCaWcgSW50ZWdlciBwcmlt\nYXJ5IGtleXMgYW5kCiAgYSBbc2VudGluZWwgY29sdW1uXShodHRwczovL2Rv\nY3Muc3FsYWxjaGVteS5vcmcvZW4vMjAvY29yZS9jb25uZWN0aW9ucy5odG1s\nI2NvbmZpZ3VyaW5nLXNlbnRpbmVsLWNvbHVtbnMpLgotIFN5bmNocm9ub3Vz\nIGFuZCBhc3luY2hyb25vdXMgcmVwb3NpdG9yaWVzIGZlYXR1cmluZzoKICAg\nIC0gQ29tbW9uIENSVUQgb3BlcmF0aW9ucyBmb3IgU1FMQWxjaGVteSBtb2Rl\nbHMKICAgIC0gQnVsayBpbnNlcnRzLCB1cGRhdGVzLCB1cHNlcnRzLCBhbmQg\nZGVsZXRlcyB3aXRoIGRpYWxlY3Qtc3BlY2lmaWMgZW5oYW5jZW1lbnRzCiAg\nICAtIEludGVncmF0ZWQgY291bnRzLCBwYWdpbmF0aW9uLCBzb3J0aW5nLCBm\naWx0ZXJpbmcgd2l0aCBgTElLRWAsIGBJTmAsIGFuZCBkYXRlcyBiZWZvcmUg\nYW5kL29yIGFmdGVyLgotIFRlc3RlZCBzdXBwb3J0IGZvciBtdWx0aXBsZSBk\nYXRhYmFzZSBiYWNrZW5kcyBpbmNsdWRpbmc6CiAgICAtIFNRTGl0ZSB2aWEg\nW2Fpb3NxbGl0ZV0oaHR0cHM6Ly9haW9zcWxpdGUub21uaWxpYi5kZXYvZW4v\nc3RhYmxlLykgb3IgW3NxbGl0ZV0oaHR0cHM6Ly9kb2NzLnB5dGhvbi5vcmcv\nMy9saWJyYXJ5L3NxbGl0ZTMuaHRtbCkKICAgIC0gUG9zdGdyZXMgdmlhIFth\nc3luY3BnXShodHRwczovL21hZ2ljc3RhY2suZ2l0aHViLmlvL2FzeW5jcGcv\nY3VycmVudC8pIG9yIFtwc3ljb3BnMyAoYXN5bmMgb3Igc3luYyldKGh0dHBz\nOi8vd3d3LnBzeWNvcGcub3JnL3BzeWNvcGczLykKICAgIC0gTXlTUUwgdmlh\nIFthc3luY215XShodHRwczovL2dpdGh1Yi5jb20vbG9uZzJpY2UvYXN5bmNt\neSkKICAgIC0gT3JhY2xlIHZpYSBbb3JhY2xlZGIgKGFzeW5jIG9yIHN5bmMp\nXShodHRwczovL29yYWNsZS5naXRodWIuaW8vcHl0aG9uLW9yYWNsZWRiLykg\nKHRlc3RlZCBvbiAxOGMgYW5kIDIzYykKICAgIC0gR29vZ2xlIFNwYW5uZXIg\ndmlhIFtzcGFubmVyLXNxbGFsY2hlbXldKGh0dHBzOi8vZ2l0aHViLmNvbS9n\nb29nbGVhcGlzL3B5dGhvbi1zcGFubmVyLXNxbGFsY2hlbXkvKQogICAgLSBE\ndWNrREIgdmlhIFtkdWNrZGJfZW5naW5lXShodHRwczovL2dpdGh1Yi5jb20v\nTWF1c2UvZHVja2RiX2VuZ2luZSkKICAgIC0gTWljcm9zb2Z0IFNRTCBTZXJ2\nZXIgdmlhIFtweW9kYmNdKGh0dHBzOi8vZ2l0aHViLmNvbS9ta2xlZWhhbW1l\nci9weW9kYmMpIG9yIFthaW9vZGJjXShodHRwczovL2dpdGh1Yi5jb20vYWlv\nLWxpYnMvYWlvb2RiYykKICAgIC0gQ29ja3JvYWNoREIgdmlhIFtzcWxhbGNo\nZW15LWNvY2tyb2FjaGRiIChhc3luYyBvciBzeW5jKV0oaHR0cHM6Ly9naXRo\ndWIuY29tL2NvY2tyb2FjaGRiL3NxbGFsY2hlbXktY29ja3JvYWNoZGIpCi0g\nLi4uYW5kIG11Y2ggbW9yZQoKIyMgVXNhZ2UKCiMjIyBJbnN0YWxsYXRpb24K\nCmBgYHNoZWxsCnBpcCBpbnN0YWxsIGFkdmFuY2VkLWFsY2hlbXkKYGBgCgo+\nIFshSU1QT1JUQU5UXVwKPiBDaGVjayBvdXQgW3RoZSBpbnN0YWxsYXRpb24g\nZ3VpZGVdW2luc3RhbGwtZ3VpZGVdIGluIG91ciBvZmZpY2lhbCBkb2N1bWVu\ndGF0aW9uIQoKIyMjIFJlcG9zaXRvcmllcwoKQWR2YW5jZWQgQWxjaGVteSBp\nbmNsdWRlcyBhIHNldCBvZiBhc3luY2hyb25vdXMgYW5kIHN5bmNocm9ub3Vz\nIHJlcG9zaXRvcnkgY2xhc3NlcyBmb3IgZWFzeSBDUlVECm9wZXJhdGlvbnMg\nb24geW91ciBTUUxBbGNoZW15IG1vZGVscy4KPCEtLSBtYXJrZG93bmxpbnQt\nZGlzYWJsZSAtLT4KPGRldGFpbHM+CjxzdW1tYXJ5PkNsaWNrIHRvIGV4cGFu\nZCB0aGUgZXhhbXBsZTwvc3VtbWFyeT4KPCEtLSBtYXJrZG93bmxpbnQtcmVz\ndG9yZSAtLT4KCmBgYHB5dGhvbgpmcm9tIGFkdmFuY2VkX2FsY2hlbXkgaW1w\nb3J0IGJhc2UsIHJlcG9zaXRvcnksIGNvbmZpZwpmcm9tIHNxbGFsY2hlbXkg\naW1wb3J0IGNyZWF0ZV9lbmdpbmUKZnJvbSBzcWxhbGNoZW15Lm9ybSBpbXBv\ncnQgTWFwcGVkLCBzZXNzaW9ubWFrZXIKCgpjbGFzcyBVc2VyKGJhc2UuVVVJ\nREJhc2UpOgogICAgIyB5b3UgY2FuIG9wdGlvbmFsbHkgb3ZlcnJpZGUgdGhl\nIGdlbmVyYXRlZCB0YWJsZSBuYW1lIGJ5IG1hbnVhbGx5IHNldHRpbmcgaXQu\nCiAgICBfX3RhYmxlbmFtZV9fID0gInVzZXJfYWNjb3VudCIgICMgdHlwZTog\naWdub3JlW2Fzc2lnbm1lbnRdCiAgICBlbWFpbDogTWFwcGVkW3N0cl0KICAg\nIG5hbWU6IE1hcHBlZFtzdHJdCgoKY2xhc3MgVXNlclJlcG9zaXRvcnkocmVw\nb3NpdG9yeS5TUUxBbGNoZW15U3luY1JlcG9zaXRvcnlbVXNlcl0pOgogICAg\nIiIiVXNlciByZXBvc2l0b3J5LiIiIgoKICAgIG1vZGVsX3R5cGUgPSBVc2Vy\nCgoKZGIgPSBjb25maWcuU1FMQWxjaGVteVN5bmNDb25maWcoY29ubmVjdGlv\nbl9zdHJpbmc9ImR1Y2tkYjovLy86bWVtb3J5OiIsIHNlc3Npb25fY29uZmln\nPWNvbmZpZy5TeW5jU2Vzc2lvbkNvbmZpZyhleHBpcmVfb25fY29tbWl0PUZh\nbHNlKSkKCiMgSW5pdGlhbGl6ZXMgdGhlIGRhdGFiYXNlLgp3aXRoIGRiLmdl\ndF9lbmdpbmUoKS5iZWdpbigpIGFzIGNvbm46CiAgICBVc2VyLm1ldGFkYXRh\nLmNyZWF0ZV9hbGwoY29ubikKCndpdGggZGIuZ2V0X3Nlc3Npb24oKSBhcyBk\nYl9zZXNzaW9uOgogICAgcmVwbyA9IFVzZXJSZXBvc2l0b3J5KHNlc3Npb249\nZGJfc2Vzc2lvbikKICAgICMgMSkgQ3JlYXRlIG11bHRpcGxlIHVzZXJzIHdp\ndGggYGFkZF9tYW55YAogICAgYnVsa191c2VycyA9IFsKICAgICAgICB7ImVt\nYWlsIjogJ2NvZHlAbGl0ZXN0YXIuZGV2JywgJ25hbWUnOiAnQ29keSd9LAog\nICAgICAgIHsiZW1haWwiOiAnamFuZWtAbGl0ZXN0YXIuZGV2JywgJ25hbWUn\nOiAnSmFuZWsnfSwKICAgICAgICB7ImVtYWlsIjogJ3BldGVyQGxpdGVzdGFy\nLmRldicsICduYW1lJzogJ1BldGVyJ30sCiAgICAgICAgeyJlbWFpbCI6ICdq\nYWNvYkBsaXRlc3Rhci5kZXYnLCAnbmFtZSc6ICdKYWNvYid9CiAgICBdCiAg\nICBvYmpzID0gcmVwby5hZGRfbWFueShbVXNlcigqKnJhd191c2VyKSBmb3Ig\ncmF3X3VzZXIgaW4gYnVsa191c2Vyc10pCiAgICBkYl9zZXNzaW9uLmNvbW1p\ndCgpCiAgICBwcmludChmIkNyZWF0ZWQge2xlbihvYmpzKX0gbmV3IG9iamVj\ndHMuIikKCiAgICAjIDIpIFNlbGVjdCBwYWdpbmF0ZWQgZGF0YSBhbmQgdG90\nYWwgcm93IGNvdW50LiAgUGFzcyBhZGRpdGlvbmFsIGZpbHRlcnMgYXMga3dh\ncmdzCiAgICBjcmVhdGVkX29ianMsIHRvdGFsX29ianMgPSByZXBvLmxpc3Rf\nYW5kX2NvdW50KExpbWl0T2Zmc2V0KGxpbWl0PTEwLCBvZmZzZXQ9MCksIG5h\nbWU9IkNvZHkiKQogICAgcHJpbnQoZiJTZWxlY3RlZCB7bGVuKGNyZWF0ZWRf\nb2Jqcyl9IHJlY29yZHMgb3V0IG9mIGEgdG90YWwgb2Yge3RvdGFsX29ianN9\nLiIpCgogICAgIyAzKSBMZXQncyByZW1vdmUgdGhlIGJhdGNoIG9mIHJlY29y\nZHMgc2VsZWN0ZWQuCiAgICBkZWxldGVkX29ianMgPSByZXBvLmRlbGV0ZV9t\nYW55KFtuZXdfb2JqLmlkIGZvciBuZXdfb2JqIGluIGNyZWF0ZWRfb2Jqc10p\nCiAgICBwcmludChmIlJlbW92ZWQge2xlbihkZWxldGVkX29ianMpfSByZWNv\ncmRzIG91dCBvZiBhIHRvdGFsIG9mIHt0b3RhbF9vYmpzfS4iKQoKICAgICMg\nNCkgTGV0J3MgY291bnQgdGhlIHJlbWFpbmluZyByb3dzCiAgICByZW1haW5p\nbmdfY291bnQgPSByZXBvLmNvdW50KCkKICAgIHByaW50KGYiRm91bmQge3Jl\nbWFpbmluZ19jb3VudH0gcmVtYWluaW5nIHJlY29yZHMgYWZ0ZXIgZGVsZXRl\nLiIpCmBgYAoKPC9kZXRhaWxzPgoKRm9yIGEgZnVsbCBzdGFuZGFsb25lIGV4\nYW1wbGUsIHNlZSB0aGUgc2FtcGxlIFtoZXJlXVtzdGFuZGFsb25lLWV4YW1w\nbGVdCgojIyMgU2VydmljZXMKCkFkdmFuY2VkIEFsY2hlbXkgaW5jbHVkZXMg\nYW4gYWRkaXRpb25hbCBzZXJ2aWNlIGNsYXNzIHRvIG1ha2Ugd29ya2luZyB3\naXRoIGEgcmVwb3NpdG9yeSBlYXNpZXIuClRoaXMgY2xhc3MgaXMgZGVzaWdu\nZWQgdG8gYWNjZXB0IGRhdGEgYXMgYSBkaWN0aW9uYXJ5IG9yIFNRTEFsY2hl\nbXkgbW9kZWwsCmFuZCBpdCB3aWxsIGhhbmRsZSB0aGUgdHlwZSBjb252ZXJz\naW9ucyBmb3IgeW91Lgo8IS0tIG1hcmtkb3dubGludC1kaXNhYmxlIC0tPgo8\nZGV0YWlscz4KPHN1bW1hcnk+SGVyZSdzIHRoZSBzYW1lIGV4YW1wbGUgZnJv\nbSBhYm92ZSBidXQgdXNpbmcgYSBzZXJ2aWNlIHRvIGNyZWF0ZSB0aGUgZGF0\nYTo8L3N1bW1hcnk+CjwhLS0gbWFya2Rvd25saW50LXJlc3RvcmUgLS0+Cgpg\nYGBweXRob24KZnJvbSBhZHZhbmNlZF9hbGNoZW15IGltcG9ydCBiYXNlLCBy\nZXBvc2l0b3J5LCBmaWx0ZXJzLCBzZXJ2aWNlLCBjb25maWcKZnJvbSBzcWxh\nbGNoZW15IGltcG9ydCBjcmVhdGVfZW5naW5lCmZyb20gc3FsYWxjaGVteS5v\ncm0gaW1wb3J0IE1hcHBlZCwgc2Vzc2lvbm1ha2VyCgoKY2xhc3MgVXNlcihi\nYXNlLlVVSURCYXNlKToKICAgICMgeW91IGNhbiBvcHRpb25hbGx5IG92ZXJy\naWRlIHRoZSBnZW5lcmF0ZWQgdGFibGUgbmFtZSBieSBtYW51YWxseSBzZXR0\naW5nIGl0LgogICAgX190YWJsZW5hbWVfXyA9ICJ1c2VyX2FjY291bnQiICAj\nIHR5cGU6IGlnbm9yZVthc3NpZ25tZW50XQogICAgZW1haWw6IE1hcHBlZFtz\ndHJdCiAgICBuYW1lOiBNYXBwZWRbc3RyXQoKY2xhc3MgVXNlclNlcnZpY2Uo\nc2VydmljZS5TUUxBbGNoZW15U3luY1JlcG9zaXRvcnlTZXJ2aWNlW1VzZXJd\nKToKICAgICIiIlVzZXIgcmVwb3NpdG9yeS4iIiIKICAgIGNsYXNzIFJlcG8o\ncmVwb3NpdG9yeS5TUUxBbGNoZW15U3luY1JlcG9zaXRvcnlbVXNlcl0pOgog\nICAgICAgICIiIlVzZXIgcmVwb3NpdG9yeS4iIiIKCiAgICAgICAgbW9kZWxf\ndHlwZSA9IFVzZXIKCiAgICByZXBvc2l0b3J5X3R5cGUgPSBSZXBvCgpkYiA9\nIGNvbmZpZy5TUUxBbGNoZW15U3luY0NvbmZpZyhjb25uZWN0aW9uX3N0cmlu\nZz0iZHVja2RiOi8vLzptZW1vcnk6Iiwgc2Vzc2lvbl9jb25maWc9Y29uZmln\nLlN5bmNTZXNzaW9uQ29uZmlnKGV4cGlyZV9vbl9jb21taXQ9RmFsc2UpKQoK\nIyBJbml0aWFsaXplcyB0aGUgZGF0YWJhc2UuCndpdGggZGIuZ2V0X2VuZ2lu\nZSgpLmJlZ2luKCkgYXMgY29ubjoKICAgIFVzZXIubWV0YWRhdGEuY3JlYXRl\nX2FsbChjb25uKQoKd2l0aCBkYi5nZXRfc2Vzc2lvbigpIGFzIGRiX3Nlc3Np\nb246CiAgICBzZXJ2aWNlID0gVXNlclNlcnZpY2Uoc2Vzc2lvbj1kYl9zZXNz\naW9uKQogICAgIyAxKSBDcmVhdGUgbXVsdGlwbGUgdXNlcnMgd2l0aCBgYWRk\nX21hbnlgCiAgICBvYmpzID0gc2VydmljZS5jcmVhdGVfbWFueShbCiAgICAg\nICAgeyJlbWFpbCI6ICdjb2R5QGxpdGVzdGFyLmRldicsICduYW1lJzogJ0Nv\nZHknfSwKICAgICAgICB7ImVtYWlsIjogJ2phbmVrQGxpdGVzdGFyLmRldics\nICduYW1lJzogJ0phbmVrJ30sCiAgICAgICAgeyJlbWFpbCI6ICdwZXRlckBs\naXRlc3Rhci5kZXYnLCAnbmFtZSc6ICdQZXRlcid9LAogICAgICAgIHsiZW1h\naWwiOiAnamFjb2JAbGl0ZXN0YXIuZGV2JywgJ25hbWUnOiAnSmFjb2InfQog\nICAgXSkKICAgIHByaW50KG9ianMpCiAgICBwcmludChmIkNyZWF0ZWQge2xl\nbihvYmpzKX0gbmV3IG9iamVjdHMuIikKCiAgICAjIDIpIFNlbGVjdCBwYWdp\nbmF0ZWQgZGF0YSBhbmQgdG90YWwgcm93IGNvdW50LiAgUGFzcyBhZGRpdGlv\nbmFsIGZpbHRlcnMgYXMga3dhcmdzCiAgICBjcmVhdGVkX29ianMsIHRvdGFs\nX29ianMgPSBzZXJ2aWNlLmxpc3RfYW5kX2NvdW50KExpbWl0T2Zmc2V0KGxp\nbWl0PTEwLCBvZmZzZXQ9MCksIG5hbWU9IkNvZHkiKQogICAgcHJpbnQoZiJT\nZWxlY3RlZCB7bGVuKGNyZWF0ZWRfb2Jqcyl9IHJlY29yZHMgb3V0IG9mIGEg\ndG90YWwgb2Yge3RvdGFsX29ianN9LiIpCgogICAgIyAzKSBMZXQncyByZW1v\ndmUgdGhlIGJhdGNoIG9mIHJlY29yZHMgc2VsZWN0ZWQuCiAgICBkZWxldGVk\nX29ianMgPSBzZXJ2aWNlLmRlbGV0ZV9tYW55KFtuZXdfb2JqLmlkIGZvciBu\nZXdfb2JqIGluIGNyZWF0ZWRfb2Jqc10pCiAgICBwcmludChmIlJlbW92ZWQg\ne2xlbihkZWxldGVkX29ianMpfSByZWNvcmRzIG91dCBvZiBhIHRvdGFsIG9m\nIHt0b3RhbF9vYmpzfS4iKQoKICAgICMgNCkgTGV0J3MgY291bnQgdGhlIHJl\nbWFpbmluZyByb3dzCiAgICByZW1haW5pbmdfY291bnQgPSBzZXJ2aWNlLmNv\ndW50KCkKICAgIHByaW50KGYiRm91bmQge3JlbWFpbmluZ19jb3VudH0gcmVt\nYWluaW5nIHJlY29yZHMgYWZ0ZXIgZGVsZXRlLiIpCmBgYAoKPC9kZXRhaWxz\nPgoKIyMjIFdlYiBGcmFtZXdvcmtzCgpBZHZhbmNlZCBBbGNoZW15IHdvcmtz\nIHdpdGggbmVhcmx5IGFsbCBQeXRob24gd2ViIGZyYW1ld29ya3MuClNldmVy\nYWwgaGVscGVycyBmb3IgcG9wdWxhciBsaWJyYXJpZXMgYXJlIGluY2x1ZGVk\nLCBhbmQgYWRkaXRpb25hbCBQUnMgdG8gc3VwcG9ydCBvdGhlcnMgYXJlIHdl\nbGNvbWVkLgoKIyMjIyBMaXRlc3RhcgoKQWR2YW5jZWQgQWxjaGVteSBpcyB0\naGUgb2ZmaWNpYWwgU1FMQWxjaGVteSBpbnRlZ3JhdGlvbiBmb3IgTGl0ZXN0\nYXIuCgpJbiBhZGRpdGlvbiB0byBpbnN0YWxsaW5nIHdpdGggYHBpcCBpbnN0\nYWxsIGFkdmFuY2VkLWFsY2hlbXlgLAppdCBjYW4gYWxzbyBiZSBpbnN0YWxs\nZWQgYXMgYSBMaXRlc3RhciBleHRyYSB3aXRoIGBwaXAgaW5zdGFsbCBsaXRl\nc3RhcltzcWxhbGNoZW15XWAuCgo8IS0tIG1hcmtkb3dubGludC1kaXNhYmxl\nIC0tPgo8ZGV0YWlscz4KPHN1bW1hcnk+TGl0ZXN0YXIgRXhhbXBsZTwvc3Vt\nbWFyeT4KPCEtLSBtYXJrZG93bmxpbnQtcmVzdG9yZSAtLT4KCmBgYHB5dGhv\nbgpmcm9tIGxpdGVzdGFyIGltcG9ydCBMaXRlc3Rhcgpmcm9tIGxpdGVzdGFy\nLnBsdWdpbnMuc3FsYWxjaGVteSBpbXBvcnQgU1FMQWxjaGVteVBsdWdpbiwg\nU1FMQWxjaGVteUFzeW5jQ29uZmlnCiMgYWx0ZXJuYXRlbHkuLi4KIyBmcm9t\nIGFkdmFuY2VkX2FsY2hlbXkuZXh0ZW5zaW9ucy5saXRlc3RhciBpbXBvcnQg\nU1FMQWxjaGVteUFzeW5jQ29uZmlnLCBTUUxBbGNoZW15UGx1Z2luCgphbGNo\nZW15ID0gU1FMQWxjaGVteVBsdWdpbigKICBjb25maWc9U1FMQWxjaGVteUFz\neW5jQ29uZmlnKGNvbm5lY3Rpb25fc3RyaW5nPSJzcWxpdGUrYWlvc3FsaXRl\nOi8vL3Rlc3Quc3FsaXRlIiksCikKYXBwID0gTGl0ZXN0YXIocGx1Z2lucz1b\nYWxjaGVteV0pCmBgYAoKPC9kZXRhaWxzPgoKRm9yIGEgZnVsbCBMaXRlc3Rh\nciBleGFtcGxlLCBjaGVjayBbaGVyZV1bbGl0ZXN0YXItZXhhbXBsZV0KCiMj\nIyMgRmxhc2sKCjwhLS0gbWFya2Rvd25saW50LWRpc2FibGUgLS0+CjxkZXRh\naWxzPgo8c3VtbWFyeT5GbGFzayBFeGFtcGxlPC9zdW1tYXJ5Pgo8IS0tIG1h\ncmtkb3dubGludC1yZXN0b3JlIC0tPgoKYGBgcHl0aG9uCmZyb20gZmxhc2sg\naW1wb3J0IEZsYXNrCmZyb20gYWR2YW5jZWRfYWxjaGVteS5leHRlbnNpb25z\nLmZsYXNrIGltcG9ydCBBZHZhbmNlZEFsY2hlbXksIFNRTEFsY2hlbXlTeW5j\nQ29uZmlnCgphcHAgPSBGbGFzayhfX25hbWVfXykKYWxjaGVteSA9IEFkdmFu\nY2VkQWxjaGVteSgKICAgIGNvbmZpZz1TUUxBbGNoZW15U3luY0NvbmZpZyhj\nb25uZWN0aW9uX3N0cmluZz0iZHVja2RiOi8vLzptZW1vcnk6IiksIGFwcD1h\ncHAsCikKYGBgCgo8L2RldGFpbHM+CgpGb3IgYSBmdWxsIEZsYXNrIGV4YW1w\nbGUsIHNlZSBbaGVyZV1bZmxhc2stZXhhbXBsZV0KCiMjIyMgRmFzdEFQSQoK\nPCEtLSBtYXJrZG93bmxpbnQtZGlzYWJsZSAtLT4KPGRldGFpbHM+CjxzdW1t\nYXJ5PkZhc3RBUEkgRXhhbXBsZTwvc3VtbWFyeT4KPCEtLSBtYXJrZG93bmxp\nbnQtcmVzdG9yZSAtLT4KCmBgYHB5dGhvbgpmcm9tIGFkdmFuY2VkX2FsY2hl\nbXkuZXh0ZW5zaW9ucy5mYXN0YXBpIGltcG9ydCBBZHZhbmNlZEFsY2hlbXks\nIFNRTEFsY2hlbXlBc3luY0NvbmZpZwpmcm9tIGZhc3RhcGkgaW1wb3J0IEZh\nc3RBUEkKCmFwcCA9IEZhc3RBUEkoKQphbGNoZW15ID0gQWR2YW5jZWRBbGNo\nZW15KAogICAgY29uZmlnPVNRTEFsY2hlbXlBc3luY0NvbmZpZyhjb25uZWN0\naW9uX3N0cmluZz0ic3FsaXRlK2Fpb3NxbGl0ZTovLy90ZXN0LnNxbGl0ZSIp\nLCBhcHA9YXBwLAopCmBgYAoKPC9kZXRhaWxzPgoKRm9yIGEgZnVsbCBGYXN0\nQVBJIGV4YW1wbGUgd2l0aCBvcHRpb25hbCBDTEkgaW50ZWdyYXRpb24sIHNl\nZSBbaGVyZV1bZmFzdGFwaS1leGFtcGxlXQoKIyMjIyBTdGFybGV0dGUKCjwh\nLS0gbWFya2Rvd25saW50LWRpc2FibGUgLS0+CjxkZXRhaWxzPgo8c3VtbWFy\neT5QcmUtYnVpbHQgRXhhbXBsZSBBcHBzPC9zdW1tYXJ5Pgo8IS0tIG1hcmtk\nb3dubGludC1yZXN0b3JlIC0tPgoKYGBgcHl0aG9uCmZyb20gYWR2YW5jZWRf\nYWxjaGVteS5leHRlbnNpb25zLnN0YXJsZXR0ZSBpbXBvcnQgQWR2YW5jZWRB\nbGNoZW15LCBTUUxBbGNoZW15QXN5bmNDb25maWcKZnJvbSBzdGFybGV0dGUu\nYXBwbGljYXRpb25zIGltcG9ydCBTdGFybGV0dGUKCmFwcCA9IFN0YXJsZXR0\nZSgpCmFsY2hlbXkgPSBBZHZhbmNlZEFsY2hlbXkoCiAgICBjb25maWc9U1FM\nQWxjaGVteUFzeW5jQ29uZmlnKGNvbm5lY3Rpb25fc3RyaW5nPSJzcWxpdGUr\nYWlvc3FsaXRlOi8vL3Rlc3Quc3FsaXRlIiksIGFwcD1hcHAsCikKYGBgCgo8\nL2RldGFpbHM+CgojIyMjIFNhbmljCgo8IS0tIG1hcmtkb3dubGludC1kaXNh\nYmxlIC0tPgo8ZGV0YWlscz4KPHN1bW1hcnk+UHJlLWJ1aWx0IEV4YW1wbGUg\nQXBwczwvc3VtbWFyeT4KPCEtLSBtYXJrZG93bmxpbnQtcmVzdG9yZSAtLT4K\nCmBgYHB5dGhvbgpmcm9tIHNhbmljIGltcG9ydCBTYW5pYwpmcm9tIHNhbmlj\nX2V4dCBpbXBvcnQgRXh0ZW5kCgpmcm9tIGFkdmFuY2VkX2FsY2hlbXkuZXh0\nZW5zaW9ucy5zYW5pYyBpbXBvcnQgQWR2YW5jZWRBbGNoZW15LCBTUUxBbGNo\nZW15QXN5bmNDb25maWcKCmFwcCA9IFNhbmljKCJBbGNoZW15U2FuaWNBcHAi\nKQphbGNoZW15ID0gQWR2YW5jZWRBbGNoZW15KAogICAgc3FsYWxjaGVteV9j\nb25maWc9U1FMQWxjaGVteUFzeW5jQ29uZmlnKGNvbm5lY3Rpb25fc3RyaW5n\nPSJzcWxpdGUrYWlvc3FsaXRlOi8vL3Rlc3Quc3FsaXRlIiksCikKRXh0ZW5k\nLnJlZ2lzdGVyKGFsY2hlbXkpCmBgYAoKPC9kZXRhaWxzPgoKIyMgQ29udHJp\nYnV0aW5nCgpBbGwgW0xpdGVzdGFyIE9yZ2FuaXphdGlvbl1bbGl0ZXN0YXIt\nb3JnXSBwcm9qZWN0cyB3aWxsIGFsd2F5cyBiZSBhIGNvbW11bml0eS1jZW50\nZXJlZCwgYXZhaWxhYmxlIGZvciBjb250cmlidXRpb25zIG9mIGFueSBzaXpl\nLgoKQmVmb3JlIGNvbnRyaWJ1dGluZywgcGxlYXNlIHJldmlldyB0aGUgW2Nv\nbnRyaWJ1dGlvbiBndWlkZV1bY29udHJpYnV0aW5nXS4KCklmIHlvdSBoYXZl\nIGFueSBxdWVzdGlvbnMsIHJlYWNoIG91dCB0byB1cyBvbiBbRGlzY29yZF1b\nZGlzY29yZF0sIG91ciBvcmctd2lkZSBbR2l0SHViIGRpc2N1c3Npb25zXVts\naXRlc3Rhci1kaXNjdXNzaW9uc10gcGFnZSwKb3IgdGhlIFtwcm9qZWN0LXNw\nZWNpZmljIEdpdEh1YiBkaXNjdXNzaW9ucyBwYWdlXVtwcm9qZWN0LWRpc2N1\nc3Npb25zXS4KCjwhLS0gbWFya2Rvd25saW50LWRpc2FibGUgLS0+CjxociAv\nPgo8cCBhbGlnbj0iY2VudGVyIj4KICA8IS0tIGdpdGh1Yi1iYW5uZXItc3Rh\ncnQgLS0+CiAgPGltZyBzcmM9Imh0dHBzOi8vcmF3LmdpdGh1YnVzZXJjb250\nZW50LmNvbS9saXRlc3Rhci1vcmcvYnJhbmRpbmcvbWFpbi9hc3NldHMvQnJh\nbmRpbmclMjAtJTIwU1ZHJTIwLSUyMFRyYW5zcGFyZW50L09yZ2FuaXphdGlv\nbiUyMFByb2plY3QlMjAtJTIwQmFubmVyJTIwLSUyMElubGluZSUyMC0lMjBE\nYXJrLnN2ZyIgYWx0PSJMaXRlc3RhciBMb2dvIC0gTGlnaHQiIHdpZHRoPSI0\nMCUiIGhlaWdodD0iYXV0byIgLz4KICA8YnI+QW4gb2ZmaWNpYWwgPGEgaHJl\nZj0iaHR0cHM6Ly9naXRodWIuY29tL2xpdGVzdGFyLW9yZyI+TGl0ZXN0YXIg\nT3JnYW5pemF0aW9uPC9hPiBQcm9qZWN0CiAgPCEtLSBnaXRodWItYmFubmVy\nLWVuZCAtLT4KPC9wPgoKW2xpdGVzdGFyLW9yZ106IGh0dHBzOi8vZ2l0aHVi\nLmNvbS9saXRlc3Rhci1vcmcKW2NvbnRyaWJ1dGluZ106IGh0dHBzOi8vZG9j\ncy5hZHZhbmNlZC1hbGNoZW15LmxpdGVzdGFyLmRldi9sYXRlc3QvY29udHJp\nYnV0aW9uLWd1aWRlLmh0bWwKW2Rpc2NvcmRdOiBodHRwczovL2Rpc2NvcmQu\nZ2cvbGl0ZXN0YXIKW2xpdGVzdGFyLWRpc2N1c3Npb25zXTogaHR0cHM6Ly9n\naXRodWIuY29tL29yZ3MvbGl0ZXN0YXItb3JnL2Rpc2N1c3Npb25zCltwcm9q\nZWN0LWRpc2N1c3Npb25zXTogaHR0cHM6Ly9naXRodWIuY29tL2xpdGVzdGFy\nLW9yZy9hZHZhbmNlZC1hbGNoZW15L2Rpc2N1c3Npb25zCltwcm9qZWN0LWRv\nY3NdOiBodHRwczovL2RvY3MuYWR2YW5jZWQtYWxjaGVteS5saXRlc3Rhci5k\nZXYKW2luc3RhbGwtZ3VpZGVdOiBodHRwczovL2RvY3MuYWR2YW5jZWQtYWxj\naGVteS5saXRlc3Rhci5kZXYvbGF0ZXN0LyNpbnN0YWxsYXRpb24KW2Zhc3Rh\ncGktZXhhbXBsZV06IGh0dHBzOi8vZ2l0aHViLmNvbS9saXRlc3Rhci1vcmcv\nYWR2YW5jZWQtYWxjaGVteS9ibG9iL21haW4vZXhhbXBsZXMvZmFzdGFwaS9m\nYXN0YXBpX3NlcnZpY2UucHkKW2ZsYXNrLWV4YW1wbGVdOiBodHRwczovL2dp\ndGh1Yi5jb20vbGl0ZXN0YXItb3JnL2FkdmFuY2VkLWFsY2hlbXkvYmxvYi9t\nYWluL2V4YW1wbGVzL2ZsYXNrL2ZsYXNrX3NlcnZpY2VzLnB5CltsaXRlc3Rh\nci1leGFtcGxlXTogaHR0cHM6Ly9naXRodWIuY29tL2xpdGVzdGFyLW9yZy9h\nZHZhbmNlZC1hbGNoZW15L2Jsb2IvbWFpbi9leGFtcGxlcy9saXRlc3Rhci9s\naXRlc3Rhcl9zZXJ2aWNlLnB5CltzdGFuZGFsb25lLWV4YW1wbGVdOiBodHRw\nczovL2dpdGh1Yi5jb20vbGl0ZXN0YXItb3JnL2FkdmFuY2VkLWFsY2hlbXkv\nYmxvYi9tYWluL2V4YW1wbGVzL3N0YW5kYWxvbmUucHkK\n")
const { data: readmeContent } = await useAsyncData<any>(() => parseMarkdown(readme.value))

// if (plugin.value?.repo) {
//   try {
//     const readmeUrl = `https://raw.githubusercontent.com/${plugin.value.repo}/main/README.md`
//     const readmeContent = await $fetch<string>(readmeUrl).catch(() => 
//       $fetch<string>(`https://raw.githubusercontent.com/${plugin.value.repo}/main/README.md`)
//     )
    
//     if (readmeContent) {
//       // Parse the markdown content using Nuxt Content
//       const { $content } = useNuxtApp()
//       // const parsed = await parseMarkdown(readmeContent)
//       readme.value = parsed
//       console.log(parsed)
//     }
//   } catch (error) {
//     console.warn(`Could not fetch README for ${plugin.value.repo}:`, error)
//     readme.value = null
//   }
// }
// if (!plugin.value) {
//   throw createError({ statusCode: 404, statusMessage: 'Module not found', fatal: true })
// }

const ownerName = computed(() => {
  if (!plugin.value?.repo) return ''
  const [owner, name] = plugin.value.repo.split('#')[0].split('/')
  return `${owner}/${name}`
})

const links = computed(() => {
  if (!plugin.value) return []
  
  const linkList = [{
    icon: 'i-lucide-book',
    label: 'Documentation',
    to: `${plugin.value.documentation || plugin.value.website}?utm_source=litestar.dev&utm_medium=aside-plugin&utm_campaign=litestar.dev`,
    target: '_blank'
  }, {
    icon: 'i-simple-icons-github',
    label: ownerName.value,
    to: plugin.value.github,
    target: '_blank'
  }]
  
  if (plugin.value.pypi) {
    linkList.push({
      icon: 'i-simple-icons-python',
      label: plugin.value.pypi,
      to: `https://pypi.org/project/${plugin.value.pypi}`,
      target: '_blank'
    })
  }
  
  if (plugin.value.npm) {
    linkList.push({
      icon: 'i-simple-icons-npm',
      label: plugin.value.npm,
      to: `https://npmjs.org/package/${plugin.value.npm}`,
      target: '_blank'
    })
  }
  
  if (plugin.value.learn_more) {
    linkList.push({
      icon: 'i-lucide-link',
      label: 'Learn more',
      to: plugin.value.learn_more,
      target: '_blank'
    })
  }
  
  return linkList
})


const title = computed(() => plugin.value?.pypi || plugin.value?.name)
const description = computed(() => plugin.value?.description || 'A Litestar plugin')
const publishedAgo = computed(() => plugin.value?.stats?.publishedAt ? useTimeAgo(plugin.value.stats.publishedAt).value : '')
const createdAgo = computed(() => plugin.value?.stats?.createdAt ? useTimeAgo(plugin.value.stats.createdAt).value : '')

useSeoMeta({
  titleTemplate: '%s · Litestar Plugins',
  title,
  description,
  ogDescription: description,
  ogTitle: computed(() => `${title.value} · Litestar Plugins`)
})

defineOgImageComponent('Plugin', {
  plugin: plugin.value,
  headline: 'Litestar Plugins',
  title: title.value,
  description: description.value
})
</script>

<template>
  <UContainer v-if="plugin">
    <UPageHeader :description="plugin.description" :ui="{ headline: 'mb-8' }">
      <template #headline>
        <UBreadcrumb :items="[{ label: 'Plugins', to: '/plugins' }, { to: { name: 'plugins', query: { category: plugin.category } }, label: plugin.category }, { label: plugin.pypi }]" />
      </template>
      <template #title>
        <div class="flex items-center gap-4">
          <UAvatar
            :src="pluginImage(plugin.icon)"
            :icon="pluginIcon(plugin.category)"
            :alt="plugin.name"
            size="xl"
            class="-m-[4px] rounded-none bg-transparent"
          />

          <div>
            {{ plugin.pypi }}

            <UTooltip v-if="plugin.type === 'official'" text="Official plugin" class="tracking-normal">
              <UIcon name="i-lucide-medal" class="size-6 text-primary" />
            </UTooltip>
          </div>
        </div>
      </template>

      <div class="flex flex-col lg:flex-row lg:items-center gap-3 mt-4">
        <UTooltip text="Monthly NPM Downloads">
          <NuxtLink class="flex items-center gap-1.5" :to="`https://npm.chart.dev/${plugin.npm}`" target="_blank">
            <UIcon name="i-lucide-circle-arrow-down" class="size-5 shrink-0" />
            <span class="text-sm font-medium">{{ formatNumber(plugin.stats?.downloads || 0) }} downloads</span>
          </NuxtLink>
        </UTooltip>

        <span class="hidden lg:block text-muted">&bull;</span>

        <UTooltip text="GitHub Stars">
          <NuxtLink class="flex items-center gap-1.5" :to="`https://github.com/${plugin.repo}`" target="_blank">
            <UIcon name="i-lucide-star" class="size-5 shrink-0" />
            <span class="text-sm font-medium">{{ formatNumber(plugin.stars || plugin.stats?.stars || 0) }} stars</span>
          </NuxtLink>
        </UTooltip>

        <span class="hidden lg:block text-muted">&bull;</span>

        <UTooltip text="Latest Version">
          <NuxtLink class="flex items-center gap-1.5" :to="`${plugin.github}/releases`" target="_blank">
            <UIcon name="i-lucide-tag" class="size-5 shrink-0" />
            <span class="text-sm font-medium">v{{ plugin.latest_version || plugin.stats?.version }}</span>
          </NuxtLink>
        </UTooltip>

        <div class="mx-3 h-6 border-l border-gray-200 dark:border-gray-800 w-px hidden lg:block" />

        <div v-for="(maintainer, index) in plugin.maintainers" :key="maintainer.github" class="flex items-center gap-3">
          <NuxtLink :to="`https://github.com/${maintainer.github}`" target="_blank" class="flex items-center gap-1.5 hover:text-primary">
            <UAvatar provider="ipx" :src="`https://ipx.nuxt.com/f_auto,s_20x20/gh_avatar/${maintainer.github}`" :srcset="`https://ipx.nuxt.com/f_auto,s_40x40/gh_avatar/${maintainer.github} 2x`" :alt="maintainer.github" size="xs" />
            <span class="text-sm font-medium">{{ maintainer.github }}</span>
          </NuxtLink>

          <span v-if="index < plugin.maintainers.length - 1" class="hidden lg:block text-muted">&bull;</span>
        </div>
      </div>
    </UPageHeader>

    <UPage>
      <UPageBody>
        <ContentRenderer v-if="readmeContent?.body" :value="readmeContent" :components="{ a: PluginProseA, img: PluginProseImg, kbd: PluginProseKbd }" class="first:[&_picture]:block first:[&_picture]:mb-4" />
        <div v-else class="text-center py-8 text-gray-500">
          <p>No README available for this plugin.</p>
        </div>
      </UPageBody>

      <template #right>
        <UContentToc>
          <template #bottom>
            <div class="hidden lg:block space-y-6">
              <UPageLinks title="Links" :links="links" />


              <USeparator type="dashed" />
              <SocialLinks />
            </div>
          </template>
        </UContentToc>
      </template>
    </UPage>
  </UContainer>
</template>